config/routes.rb
Sprinkler::Application.routes.draw do
  resources :gif_links do
    get :details, on: :member
  end
  resources :ember, controller: "ember", only: [ :index ]

  root 'gif_links#index'
end

app/models/gif_link.rb
class GifLink < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ember_controller.rb
class EmberController < ApplicationController
  def index
  end
end

app/controllers/gif_links_controller.rb
class GifLinksController < ApplicationController
  before_action :set_gif_link, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  # GET /gif_links
  def index
    @gif_links = GifLink.all
  end

  # GET /gif_links/1
  def show
    respond_with @gif_link
  end

  # GET /gif_links/new
  def new
    @gif_link = GifLink.new
  end

  # GET /gif_links/1/edit
  def edit
  end

  # POST /gif_links
  def create
    @gif_link = GifLink.create(gif_link_params)
    respond_with @gif_link
  end

  # PATCH/PUT /gif_links/1
  def update
    if @gif_link.update(gif_link_params)
      respond_with @gif_link
    end
  end

  # DELETE /gif_links/1
  def destroy
    @gif_link.destroy
    respond_to do |format|
      format.html {redirect_to gif_links_url}
      format.json {render nothing: true}
    end
  end

  def details
    respond_to do |format|
      format.html { render "ember/index" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif_link
      @gif_link = GifLink.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gif_link_params
      params.require(:gif_link).permit(:title, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gif_links_helper.rb
module GifLinksHelper
end

app/views/ember/index.html.erb
<% content_for :additional_javascript_includes do %>
  <%= javascript_include_tag "router" %>
<% end %>

app/views/gif_links/_form.html.erb
<%= form_for(@gif_link) do |f| %>
  <% if @gif_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gif_link.errors.count, "error") %> prohibited this gif_link from being saved:</h2>

      <ul>
      <% @gif_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="url-input-component-container">
    <!-- THIS IS REPLACED WITH AN EMBER COMPONENT -->
    <div class="field">
      Loading...
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gif_links/edit.html.erb
<h1>Editing gif_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @gif_link %> |
<%= link_to 'Back', gif_links_path %>

app/views/gif_links/index.html.erb
<h1>Listing gif_links</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gif_links.each do |gif_link| %>
      <tr>
        <td><%= gif_link.title %></td>
        <td><%= gif_link.url %></td>
        <td><%= gif_link.description %></td>
        <td><%= link_to 'Show', gif_link %></td>
        <td><%= link_to 'Edit', edit_gif_link_path(gif_link) %></td>
        <td><%= link_to 'Destroy', gif_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gif link', new_gif_link_path %>

app/views/gif_links/new.html.erb
<h1>New gif_link</h1>

<%= render 'form' %>

<%= link_to 'Back', gif_links_path %>

app/views/gif_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gif_link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @gif_link.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gif_link.description %>
</p>

<%= link_to 'Edit', edit_gif_link_path(@gif_link) %> |
<%= link_to 'Back', gif_links_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sprinkler</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :additional_javascript_includes %>
</head>
<body>

<%= yield %>

</body>
</html>